### ISSUE TITLE
Some question about Eq.3 and Eq.5

### ISSUE THREAD

**Issue by simpler66** [fengzhang427/LLF-LUT#2]
Thanks for your great work. I still have some questions. 
Firstly, I'm unsure about how to create the adaptive Laplacian pyramid for LLF/PPB input, if you used the method in [1] without any modification. 
Secondly, I've noticed possible typos in Eq.3 where sigma is compared with i, and sigma is compared with |i-g| in [2]. So, I'm unclear if variable i in Eq.3 represents the coefficient of the adaptive Laplacian pyramid rather than the pixel value of the input HDR image. 
Thirdly, it seems that to get the refined LapPyramid, you replace user-defined alpha and beta with predicted ones, and the other steps stay the same as the original fast-LLF. But I'm not sure because Eq.5 suggests the refined LapPyramid might be obtained by mapping the adaptive Laplacian pyramid using a remapping function.
Could you please help clarify? Looking forward to your response. Thank you!

[1] Peter J Burt and Edward H Adelson. The laplacian pyramid as a compact image code. In Readings in computer vision, pages 671–679. Elsevier, 1987. 2, 3, 5
[2] Sylvain Paris, Samuel W Hasinoff, and Jan Kautz. Local laplacian filters: Edge-aware image processing with a laplacian pyramid. ACM Trans. Graph., 30(4):68, 2011. 2, 5

**Comment by fengzhang427** [comment]
Thank you for your interest in our work, I will answer your questions one by one!
1. Since we set the resolution of the bottom layer of the pyramid to be close to 64x64, thus, we can set different pyramid layers depending on the image size adaptively. For example, the resolution of the input image is [H, W], and the number of pyramid layers is set to min(H/64, W/64).
2. Sorry for the disturbance, the Eq .3 here is a reference to the formula in [1], which is an improved version of the formula in [2], thus variable i in Eq.3 still represents the coefficient of the Laplacian pyramid.
3. We remain consistent with fast-LLF in principle, but we modify the code of fast-LLF in that we split the original global remapping function into a remapping function at each layer, while each layer of the network learns a different sigma and beta.

[1]Sylvain Paris, Samuel W Hasinoff, and Jan Kautz. Local laplacian filters: Edge-aware image processing with a laplacian pyramid. ACM Trans. Graph., 30(4):68, 2011. 2, 5.
[2]Aubry, M., Paris, S., Hasinoff, S. W., Kautz, J., & Durand. Fast local laplacian filters: Theory and applications.  ACM Trans. Graph., 33(5), 2014, 1-14.

**Comment by simpler66** [comment]
Thanks for your reply！I  still want to confirm a few details. 
    1. Which method did you use to create the adaptive Laplacian pyramid, [1] or [2]? 
    2. In Eq.3, why g is subtracted from i? What's the reason for subtracting the Gaussian coefficient from the Laplacian coefficient? 
    3. If your method can be descripted as follows: The adaptive Laplacian pyramid is used to predict alpha and beta. And there's an additional process to generate another Laplacian Pyramid (called refined high-frequency component in your paper) from the input HDR image using fast-LLF with the predicted alpha and beta.


[1] Peter J Burt and Edward H Adelson. The laplacian pyramid as a compact image code. In Readings in computer vision, pages 671–679. Elsevier, 1987. 2, 3, 5
[2] Aubry, M., Paris, S., Hasinoff, S. W., Kautz, J., & Durand. Fast local laplacian filters: Theory and applications. ACM Trans. Graph., 33(5), 2014, 1-14.

**Comment by fengzhang427** [comment]
1. We utilize [2] to create the adaptive Laplacian pyramid.
2. In Eq.3, I minus g represents the image intensity at the location and scale where we compute the output pyramid coefficient. Intuitively, pixels closer than \sigma to g should be processed as details and those farther than sr away should be processed as edges. For more details, please refer to [1] and [2].
3. Not exactly. Our method can be described as follows: First, we decompose the input HDR image into adaptive Laplacian pyramid. Then, we enhance the bottom layer (low-frequency component) with 3D-LUT, and we utilize the enhanced low-frequency component and Laplacian layer (high-frequency component) to predict alpha and beta at each layer. After obtaining the predicted alpha and beta, we can utilize them to feed into fast-LLF to enhance the Laplacian layer (high-frequency component) form adaptive Laplacian pyramid, thus, we get the refined high-frequency component. At last, we reconstruct the pyramid to obtain the output SDR image with the enhanced low-frequency component and the refined high-frequency component.

[1]Sylvain Paris, Samuel W Hasinoff, and Jan Kautz. Local laplacian filters: Edge-aware image processing with a laplacian pyramid. ACM Trans. Graph., 30(4):68, 2011. 2, 5.
[2]Aubry, M., Paris, S., Hasinoff, S. W., Kautz, J., & Durand. Fast local laplacian filters: Theory and applications. ACM Trans. Graph., 33(5), 2014, 1-14.

**Comment by simpler66** [comment]
Thank you for your response and help. Looking forward to your open-source code.

**Comment by simpler66** [comment]
what parameters are you used, such as alpha and beta, to create the adaptive Laplacian pyramid

**Comment by fengzhang427** [comment]
Creating a Laplace pyramid does not require the alpha and beta parameters, which are used for the filters. We obtained the Laplace pyramid with a Gaussian filter like the other researcher, for details you can google how to create a Laplace pyramid.
