### ISSUE TITLE
Question about unaligned HDR+ datasets

### ISSUE THREAD

**Issue by ZachL1** [fengzhang427/LLF-LUT#3]
Dear authors, thank you for your great work!

I have some questions about the HDR+ dataset you are using. I found that there are some misaligned image pairs in the original dataset downloaded according to the instructions on the page https://hdrplusdata.org/dataset.html, such as the reference image `20171106/results_20171023/3eb8_20151020_084104_198/final.jpg`:
![image](https://github.com/fengzhang427/LLF-LUT/assets/57339063/52b78827-254f-4684-a746-e59e54e799f0)

The corresponding input image `20171106/results_20171023/3eb8_20151020_084104_198/merged.dng`:
![image](https://github.com/fengzhang427/LLF-LUT/assets/57339063/94cd4fc9-76af-4651-99b9-4c5830bdb97d)
> I converted .dng to .jpg through rawpy postprocess(). This is my conversion function:
> ```
> with rawpy.imread(input_dng_file) as raw:
>     rgb = raw.postprocess(
>         use_camera_wb=True,
>         output_color=rawpy.ColorSpace.sRGB,
>         output_bps=8,
>         )
> ```

**May I ask how you obtained the data that was ultimately used for training? Did you use some kind of filtering strategy? Or is there something wrong with my post-processing method?**
I tried to find the answer from the link provided in [your README file for 480p](https://drive.google.com/drive/folders/1Y1Rv3uGiJkP6CIrNTSKxPn1p-WFAc48a), unfortunately I was denied access.

Looking forward to your reply, thanks again!

**Comment by fengzhang427** [comment]
I apologize for the broken dataset link, I'll update the new link immediately!

1. For the 4K resolution of HDR+, the original dataset indeed has a lot of unaligned data between the datasets, so we refer to [1] to filter the dataset, the details of filtering strategy can be found in [1].
2. For the 480p resolution of HDR+, we directly utilized the 480p dataset produced by 1, whose github link is as follows: [https://github.com/HuiZeng/Image-Adaptive-3DLUT](url). You can directly download the 480p dataset from their link.
3. Since the 4K resolution  dataset is oversized, we can't upload our filtered 4K dataset to google drive in China, so we will update the Baidu Netdisk link.

**Comment by fengzhang427** [comment]
[1] Wang T, Li Y, Peng J, et al. Real-time image enhancer via learnable spatial-aware 3d lookup tables[C]//Proceedings of the IEEE/CVF International Conference on Computer Vision. 2021: 2471-2480.
[2] Zeng H, Cai J, Li L, et al. Learning image-adaptive 3d lookup tables for high performance photo enhancement in real-time[J]. IEEE Transactions on Pattern Analysis and Machine Intelligence, 2020, 44(4): 2058-2073.

**Comment by ZachL1** [comment]
I see, thanks for the detailed reply!
